using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SmartInventory.API.Models;

/// <summary>
/// Represents a purchase order.
/// </summary>
[Table("PurchaseOrder")]
public class PurchaseOrder
{
    /// <summary>
    /// A unique identifier for the purchase order.
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public required int PurchaseOrderId { get; set; }

    /// <summary>
    /// Identifies the supplier to which the PO is sent.
    /// </summary>
    public required int SupplierId { get; set; }

    /// <summary>
    /// The date the PO was created.
    /// </summary>
    public required DateTime OrderDate { get; set; }

    /// <summary>
    /// The estimated date the supplier will deliver the goods.
    /// </summary>
    public DateTime ExpectedDeliveryDate { get; set; }

    /// <summary>
    /// Tracks where the PO is in the process.<br/>
    /// Possible values are: Pending, Approved, Sent, Partially Received, Completed or Canceled.
    /// </summary>
    public required string Status { get; set; }

    /// <summary>
    /// Additional comments or instructions.
    /// </summary>
    public string Notes { get; set; } = "";

    /// <summary>
    /// Indicates whether the PO was automatically generated or note. It helps with traceability.
    /// </summary>
    public bool AutoGenerated { get; set; }

    // navigation properties

    /// <summary>
    /// A purchase order may be sent to one supplier.
    /// </summary>
    public required Supplier Supplier { get; set; }

    /// <summary>
    /// A purchase order may have one or more purchase order items.
    /// </summary>
    public required List<PurchaseOrderItem> PurchaseOrderItems { get; set; } = [];
}