namespace SmartInventory.API.Domain.DTO;

/// <summary>
/// Represents a Requisition that is generated by the sales manager,
/// requesting that more stock be ordered to the procurement department.
/// </summary>
public class RequisitionFormData
{
    /// <summary>
    /// The name of the document.
    /// </summary>
    public string DocName { get; set; } = "Requisition";

    /// <summary>
    /// The number of the document.
    /// </summary>
    public int DocNo { get; set; }

    /// <summary>
    /// The name of the company.
    /// </summary>
    public string? CompanyName { get; set; }

    /// <summary>
    /// The address of the company
    /// </summary>
    public string? CompanyAddress { get; set; }

    /// <summary>
    /// The department requesting the purchase of more stock.
    /// </summary>
    public string? FromDepartment { get; set; }

    /// <summary>
    /// The date on which the Requisition was generated.
    /// </summary>
    public DateTime DateGenerated { get; set; } = DateTime.Now;

    /// <summary>
    /// The items that need to be purchased.
    /// </summary>
    public List<RequisitionDataItem> RequisitionDataItems { get; set; } = [];

    /// <summary>
    /// The name of the person who authorized the generation of the requisition.
    /// </summary>
    public string? Authorized { get; set; }
}