namespace SmartInventory.API.Domain.Models;

/// <summary>
/// Represents a report generated by the system.
/// </summary>
public class Report
{
    /// <summary>
    /// Identifies the report.
    /// </summary>
    public int ReportId { get; set; }

    /// <summary>
    /// Specifies the type of report:
    ///     1. StockReport -> Provides information on the level of stock/inventory.
    ///     2. Requisition -> Provides information to the procuremet department to purchase goods/services.
    ///     3. Quotation   -> Provides information to the customer on the pricing of goods or services.
    ///     4. Order       -> Provides information to the seller about the goods/services the customer wants.
    ///     5. Goods Received Note -> Provides information to the seller that the delivered goods have been received.
    ///     6. Delivery Note -> Provides information to the buyer on what goods/services are being delivered.
    ///     7. Tax Invoice -> A proof indicating that the buyer and seller performed a transaction.
    /// </summary>
    public string ReportType { get; set; } = "";

    /// <summary>
    /// The date on which the report was generated.
    /// </summary>
    public DateTime GeneratedOn { get; set; }

    /// <summary>
    /// The username of the user who generated the report.
    /// </summary>
    public string GeneratedByUserId { get; set; } = "";

    /// <summary>
    /// The start of the period for which the report was generated.
    /// </summary>
    public DateTime PeriodStart { get; set; }

    /// <summary>
    /// The end of the period for which the report was generated.
    /// </summary>
    public DateTime PeriodEnd { get; set; }

    /// <summary>
    /// The report result stored as JSON.
    /// </summary>
    public string? Data { get; }
}