using Microsoft.AspNetCore.Mvc;

namespace SmartInventory.API.Domain.Models;

/// <summary>
/// Represents a report generated by the system.
/// </summary>
public class Report
{
    /// <summary>
    /// Identifies the report.
    /// </summary>
    public int ReportId { get; set; }

    /// <summary>
    /// Specifies the type of report.
    /// </summary>
    public string ReportType { get; set; } = "";

    /// <summary>
    /// The date on which the report was generated.
    /// </summary>
    public DateTime GeneratedOn { get; set; }

    /// <summary>
    /// The username of the user who generated the report.
    /// </summary>
    public string GeneratedByUserId { get; set; } = "";

    /// <summary>
    /// The start of the period for which the report was generated.
    /// </summary>
    public DateTime PeriodStart { get; set; }

    /// <summary>
    /// The end of the period for which the report was generated.
    /// </summary>
    public DateTime PeriodEnd { get; set; }

    /// <summary>
    /// The report result stored as JSON.
    /// </summary>
    public string? Data { get; }
}